agenda/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^liste/$', views.liste_events, name='liste_events'),
    url(r'^listes/$', views.ListEvents.as_view(paginate_by=5), name='listes_events'),
    url(r'^listes/(?P<champ>[\w-]+)/(?P<terme>[\w-]+)/$', views.ListEvents.as_view(paginate_by=5), name='listes_events_filter'),
    url(r'^create/$', views.create_event, name='create_event'),
    url(r'^(\d+)/detail/$', views.detail_event, name='detail_event'),
    url(r'^(\d+)/guest/(\d+)/delete/$', views.delete_guest, name='delete_guest'),
    url(r'^(\d+)/delete/$', views.delete_event, name='delete_event'),
    url(r'^(\d+)/update/$', views.update_event, name='update_event'),
]

myelearning/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.views import generic
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from students.views import students, classroom, teachers

from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', generic.RedirectView.as_view(url='/course/', permanent=True)),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, name='logout'),
    url(r'^accounts/signup/$', classroom.SignupView.as_view(), name='signup'),
    url(r'^password-change/$', auth_views.password_change, name='password_change'),
    url(r'^password-change/done/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^password-reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password-reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^password-reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^admin/', admin.site.urls),
    url(r'^course/', include('courses.urls')),
    url(r'^students/', include('students.urls')),
    url(r'^calendar/', include('agenda.urls')),
    url(r'^api/', include('courses.api.urls', namespace='api')),
    url(r'^sw.js', (TemplateView.as_view(template_name="sw.js", content_type='application/javascript', )), name='sw.js'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agenda/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from students.models import User

# Create your models here.
class Event(models.Model):
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank=True, null=True)
    guests = models.ManyToManyField(User, through='EventGuest')
    date = models.DateTimeField()
    location = models.TextField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "/calendar/%s/detail/" % self.id

    def delete_url(self):
        return "/calendar/%s/delete/" % self.id


class EventGuest(models.Model):
    status_choices = (
        (0, _('Host')),
        (1, _('Guest')),
        (2, _('Desisted')),
    )
    event = models.ForeignKey(Event)
    guest = models.ForeignKey(User)
    status = models.IntegerField(choices=status_choices)

    class Meta:
        unique_together = ('event', 'guest')

    def __str__(self):
        return '{} - {}'.format(self.event, self.guest)

    def delete_url(self):
        return "/calendar/%i/guest/%i/delete/" % (self.event.id, self.guest.id)

agenda/forms.py
from django import forms
from agenda.models import Event, EventGuest
from students.models import (
    User
)


class EventForm(forms.ModelForm):

    class Meta:
        model = Event
        fields = ('name', 'description', 'date', 'location',)


class EventGuestForm(forms.ModelForm):

    class Meta:
        model = EventGuest
        fields = ('event', 'guest', 'status',)

agenda/views.py
import json
import datetime

from django.shortcuts import render, HttpResponseRedirect, render_to_response
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.template import RequestContext
from django.views.generic.list import ListView
from django.core.paginator import Paginator, InvalidPage, EmptyPage

from django.forms import HiddenInput
from agenda.models import Event
from agenda.models import EventGuest
from agenda.forms import EventForm, EventGuestForm
from students.models import User

# Create your views here.
def liste_events(request):
    events = Event.objects.all()
    paginator = Paginator(events, 10)
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1
    try:
        events = paginator.page(page)
    except (EmptyPage, InvalidPage):
        events = paginator.page(paginator.num_pages)
    return render(request, 'event/liste.html', {'events': events})


class ListEvents(ListView):

    def get_queryset(self):
        events = Event.objects.filter(
            guests = self.request.user,
            date__gte = datetime.datetime.now()
        )
        if 'champ' in self.kwargs:
            events = events.filter(
                (self.kwargs['champ'],
                self.kwargs['terme'])
            )
        return events

def create_event(request):
    if request.method == "POST":
        form = EventForm(request.POST)
        if form.is_valid():
            event = form.save()
            return HttpResponseRedirect('/calendar/%i/detail/' % event.pk)
    else:
        form = EventForm()
    return render(request, 'event/create.html', {'form': form})

def detail_event(request, id):
    event = Event.objects.get(pk=id)
    if request.method == "POST":
        form = EventGuestForm(request.POST)
        if form.is_valid():
            form.save()
            if request.is_ajax():
                delete_form = render_to_string(
                    "partial/delete_form.html",
                    {'delete_url': form.instance.delete_url()}
                )
                data = {
                    'guest': form.instance.guest.username,
                    'get_status_display' : form.instance.get_status_display(),
                    'delete_form': delete_form
                }
                return HttpResponse(
                    json.dumps(data),
                    content_type="application/json"
                )
            return HttpResponseRedirect('/calendar/%s/detail/' % id)
    else:
        form = EventGuestForm(initial={'event': event})
        guests = [user.pk for user in event.guests.all()]
        form.fields['guest'].queryset=User.objects.exclude(pk__in=guests)
        form.fields['event'].widget = HiddenInput()
    if request.is_ajax():
        render_to_response(
            'partial/guest_form.html',
            { 'event': event, 'form': form}
        )
    return render(request, 'event/detail.html', {'event': event, 'form': form})

def delete_guest(request, id, guest):
    if request.method == "POST":
        event = Event.objects.get(pk=id)
        guest = User.objects.get(pk=guest)
        to_delete = EventGuest.objects.get(
            event = event,
            guest = guest
        )
        to_delete.delete()
        if request.is_ajax():
            return HttpResponse('OK')
    return HttpResponseRedirect('/calendar/%s/detail/' % id)


def delete_event(request, id):
    if request.method == "POST":
        event = Event.objects.get(pk = id)
        event.delete()
    return HttpResponseRedirect('/calendar/liste/')

def update_event(request, id):
    event = Event.objects.get(pk = id)
    if request.method == "POST":
        form = EventForm(request.POST, instance=event)
        if form.is_valid():
            u = form.save()
            return HttpResponseRedirect('/calendar/%i/detail/' % u.pk)
    else:
        form = EventForm(instance = event)
    return render(request, 'event/create.html', {'form': form})

agenda/templates/event/create.html
{% extends "base.html" %}
{% load i18n %}
   {% block title %}
    {% trans 'Create a new event' %}
   {% endblock %}
   {% block content %}
   <div class="container"><br><br><br><br><br><br>
           <form action="" method="post" enctype="multipart/form-data">
             {{ form.as_p }}
             {% csrf_token %}
             <p><input type="submit" class="btn btn-primary" value="{% trans 'Create event' %}"></p>
           </form>
         </div>
     </div>
   {% endblock %}


   {% block domready %}
   $('#id_date').datepicker({
       dateFormat: 'yy-mm-dd',
        onSelect: function(datetext){
            var d = new Date(); // for now
            var h = d.getHours();
        		h = (h < 10) ? ('0' + h) : h ;

        		var m = d.getMinutes();
                m = (m < 10) ? ('0' + m) : m ;

                var s = d.getSeconds();
                s = (s < 10) ? ('0' + s) : s ;

        		datetext = datetext + ' ' + h + ':' + m + ':' + s;
                $('#id_date').val(datetext);
        },
   });
   {% endblock %}

agenda/templates/event/detail.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
{{ event.name }}
{% endblock %}
{% block content %}
<div class="container"><br><br><br><br><br><br>
    <div>
        <h2>{{ event.name }}</h2>
        <p>{{ event.description }}</p>
        <p>{{ event.date }}</p>
        <p>{{ event.location }}</p>
    </div>
    <div>
        {% for guest in event.eventguest_set.all %}
        <p>{{ guest.guest }}</p>
        <div>
            {{ guest.get_status_display }}
            {% with delete_url=guest.delete_url %}
            {% include 'partial/delete_form.html' %}
            {% endwith %}
        </div>
        {% endfor %}
    </div>
    <div>
        {% include 'partial/guest_form.html' %}
    </div>
</div>
{% endblock %}

{% block domready %}

    $('#guest_form').on('submit', function(e) {
        $.ajax({
            type: 'POST',
            data: $(this).serialize(),
            url: "",
            success: function(data) {
                if (typeof(data) == "string") {
                    $('#guest_form').html(data);
                } else {
                    $('#guest_form').append(
                        "<div class='well'>"
                            + data.guest + " : "
                            + data.get_status_display + ""
                            + data.delete_form +
                        "</div>"
                    )
                }
            }
        })
        e.preventDefault();
    });

    $('.delete').on('submit', function(e){
        form = $(this);
        $.ajax({
            type: "POST",
            data: $(this).serialize(),
            url: $(this).attr("action"),
            success: function(data) {
                if (data === "OK") {
                    form.parent().remove()
                }
            }
        })
        e.preventDefault();
    })

{% endblock %}

agenda/templates/event/liste.html
{% extends "base.html" %}
{% load i18n %}
   {% block title %}
    {% trans 'Events' %}
   {% endblock %}
   {% block content %}
   <div class="container"><br><br><br><br><br><br>
         <ul>
             {% for event in events %}
                <li>
                    <h3>
                        <a href="" class="titre">{{ event.name }}</a>
                        <a href="{{ event.get_absolute_url }}">({% trans 'details' %})</a>
                    </h3>
                    <div class="event">
                    <p>{{ event.date }}</p>
                    <p>{{ event.location }}</p>
                    {% for guest in event.eventguest_set.all %}
                    <div class="well">
                        {{ guest.guest }}: {{ guest.get_status_display }}
                    </div>
                    {% endfor %}
                    {% with delete_url=event.delete_url %}
                    {% include 'partial/delete_form.html' %}
                    {% endwith %}
                    <a href="{% url 'update_event' event.id %}" class="btn btn-default">{% trans 'Update' %}</a>
                    </div>
                </li>
             {% endfor %}
         </ul>

         <ul class="pagination">
             {% if events.has_previous %}
             <li><a href="?page={{ events.previous_page_number }}">{% trans 'Previous' %}</a></li>
             {% endif %}
             {% for l in events.paginator.page_range %}
                {% if forloop.counter < 5 %}
                    <li {% if l == events.number %}class="active"{% endif %}><a href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
                {% endif %}
             {% endfor %}
             {% if events.has_next %}
             <li><a href="?page={{ events.next_page_number }}">{% trans 'Next' %}</a></li>
             {% endif %}
        </ul>

         <a href="{% url 'create_event' %}" class="btn btn-primary">{% trans 'Create a new event' %}</a>
     </div>
   {% endblock %}

   {% block domready %}
   $('.event').hide();
   $('.titre').on('click', function(e) {
       $(this).parent().parent().children('.event').toggle();
       e.preventDefault();
   })
   {% endblock %}